name: Terraform Apply
on:
  push:
    branches:
      - master


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.8
    - name: Terraform Init
      run: terraform init
    - name: Print secret value
      env:
        
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      
      run: |
          echo $AWS_SECRET_KEY
          echo $AWS_SECRET_ACCESS_KEY
      
        
    # - name: Terraform Plan
    #   run: |
    #       terraform plan -var aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }} -var aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main'
      run: |
          terraform apply --auto-approve
        
